export enum ExperienceErrorCode {
  NOT_FOUND = 'EXPERIENCE_NOT_FOUND',
  INVALID_INPUT = 'EXPERIENCE_INVALID_INPUT',
  SLUG_TAKEN = 'EXPERIENCE_SLUG_TAKEN',
  ALREADY_DELETED = 'EXPERIENCE_ALREADY_DELETED',
  NOT_DELETED = 'EXPERIENCE_NOT_DELETED',
}
