export enum ProfileErrorCode {
  NOT_FOUND = 'PROFILE_NOT_FOUND',
  INVALID_INPUT = 'PROFILE_INVALID_INPUT',
  ALREADY_EXISTS = 'PROFILE_ALREADY_EXISTS',
  MEDIA_NOT_FOUND = 'PROFILE_MEDIA_NOT_FOUND',
}
