import type { DdlEntry, DdlGroup } from './ddl.types';

// `source` doubles as the live link until routes are renamed (Phase 2/3):
//   'route:/ddl/hero-variants' → that route · 'inline:#primitives' → index anchor.
export function entryLink(entry: DdlEntry): string {
  return entry.source?.startsWith('route:') ? entry.source.slice('route:'.length) : '/ddl';
}

export function entryFragment(entry: DdlEntry): string | undefined {
  return entry.source?.startsWith('inline:#') ? entry.source.slice('inline:#'.length) : undefined;
}

export function entryIsRoute(entry: DdlEntry): boolean {
  return entry.source?.startsWith('route:') ?? false;
}

// ──────── Groups (sidebar order) ─────────────────────────────────────────
// Scope ladder Foundations → Components → Sections → Pages, plus Patterns as
// the orthogonal guidance axis. See .context/plans/epic-ddl-component-docs.md.
export const DDL_GROUPS: readonly DdlGroup[] = [
  { id: 'foundations', label: 'Foundations', blurb: 'Tokens, type, color, spacing — the measurable base.' },
  { id: 'components', label: 'Components', blurb: 'Single primitives with a defined API.' },
  { id: 'sections', label: 'Sections', blurb: 'Multi-primitive page sections (organisms).' },
  { id: 'pages', label: 'Pages', blurb: 'Full-screen layouts and templates.' },
  { id: 'patterns', label: 'Patterns', blurb: 'Reusable recipes and guidance.' },
];

// ──────── Registry (source of truth) ─────────────────────────────────────
// Status is inferred from prior prose where not yet verified; confirm per page
// during the build (§7). `source` points at where the content lives today so
// the migration phases know what to move.
export const DDL_REGISTRY: readonly DdlEntry[] = [
  // ── Foundations ────────────────────────────────────────────────────────
  {
    slug: 'container',
    title: 'Container',
    group: 'foundations',
    status: 'shipped',
    summary: 'Width-constrained layout: content · wide · full.',
    source: 'route:/ddl/container',
  },
  {
    slug: 'tokens',
    title: 'Tokens',
    group: 'foundations',
    status: 'shipped',
    summary: 'Landing design tokens — color & spacing scales.',
    source: 'route:/ddl/tokens',
  },
  {
    slug: 'typography',
    title: 'Typography',
    group: 'foundations',
    status: 'shipped',
    summary: 'Three voices: Newsreader · Inter · JetBrains Mono.',
    source: 'route:/ddl/typography',
  },
  {
    slug: 'contrast',
    title: 'Contrast & color',
    group: 'foundations',
    status: 'shipped',
    summary: 'Live WCAG 2.x + APCA matrix per theme.',
    source: 'route:/ddl/contrast',
  },
  {
    slug: 'prose-flow',
    title: 'Prose flow',
    group: 'foundations',
    status: 'shipped',
    summary: 'Vertical rhythm spec for .landing-prose.',
    source: 'route:/ddl/prose-flow',
  },
  {
    slug: 'identity',
    title: 'Identity',
    group: 'foundations',
    status: 'shipped',
    summary: 'Brand system: monogram, wordmark, signature, loader.',
    source: 'route:/ddl/identity',
  },

  // ── Components ─────────────────────────────────────────────────────────
  {
    slug: 'button',
    title: 'Button',
    group: 'components',
    status: 'shipped',
    summary: 'Solid · ghost · link variants.',
    source: 'route:/ddl/button',
  },
  {
    slug: 'link',
    title: 'Link',
    group: 'components',
    status: 'shipped',
    summary: 'Navigation link with auto-detected kind.',
    source: 'route:/ddl/link',
  },
  {
    slug: 'arrow',
    title: 'Arrow',
    group: 'components',
    status: 'shipped',
    summary: 'Directional arrow icon.',
    source: 'route:/ddl/arrow',
  },
  {
    slug: 'chip',
    title: 'Chip',
    group: 'components',
    status: 'shipped',
    summary: 'Tech tag, hairline border, sm/md.',
    source: 'route:/ddl/chip',
  },
  {
    slug: 'eyebrow',
    title: 'Eyebrow',
    group: 'components',
    status: 'shipped',
    summary: 'Section label, single or array with separators.',
    source: 'route:/ddl/eyebrow',
  },
  {
    slug: 'status-dot',
    title: 'Status dot',
    group: 'components',
    status: 'shipped',
    summary: 'Live status: available · busy · away.',
    source: 'route:/ddl/status-dot',
  },
  {
    slug: 'figure',
    title: 'Figure',
    group: 'components',
    status: 'shipped',
    summary: 'Numbered caption + lazy load.',
    source: 'route:/ddl/figure',
  },
  {
    slug: 'pull-quote',
    title: 'Pull-quote',
    group: 'components',
    status: 'shipped',
    summary: 'Newsreader italic with indigo border.',
    source: 'route:/ddl/pull-quote',
  },
  {
    slug: 'section-rule',
    title: 'Section rule',
    group: 'components',
    status: 'shipped',
    summary: 'Section divider: plain / lift.',
    source: 'route:/ddl/section-rule',
  },
  {
    slug: 'segmented',
    title: 'Segmented control',
    group: 'components',
    status: 'shipped',
    summary: 'Tab/segment switcher.',
    source: 'route:/ddl/segmented',
  },
  {
    slug: 'icon',
    title: 'Icon',
    group: 'components',
    status: 'shipped',
    summary: 'Icon renderer over the supported set.',
    source: 'route:/ddl/icon',
  },
  {
    slug: 'input',
    title: 'Input',
    group: 'components',
    status: 'shipped',
    summary: 'Text input field.',
    source: 'route:/ddl/input',
  },
  {
    slug: 'back-link',
    title: 'Back link',
    group: 'components',
    status: 'shipped',
    summary: 'Back navigation button.',
    source: 'route:/ddl/back-link',
  },
  {
    slug: 'empty-state',
    title: 'Empty state',
    group: 'components',
    status: 'shipped',
    summary: 'Empty-state display.',
    source: 'route:/ddl/empty-state',
  },
  {
    slug: 'loading-spinner',
    title: 'Loading spinner',
    group: 'components',
    status: 'shipped',
    summary: 'Loading indicator.',
    source: 'route:/ddl/loading-spinner',
  },
  {
    slug: 'router-progress',
    title: 'Router progress',
    group: 'components',
    status: 'shipped',
    summary: 'Route-change progress bar.',
    source: 'route:/ddl/router-progress',
  },
  {
    slug: 'section-heading',
    title: 'Section heading',
    group: 'components',
    status: 'shipped',
    summary: 'Section heading scale variants.',
    source: 'route:/ddl/section-heading',
  },
  {
    slug: 'section-header',
    title: 'Section header',
    group: 'components',
    status: 'decided',
    summary: 'Eyebrow + center display + italic accent.',
    source: 'route:/ddl/section-header',
  },
  {
    slug: 'page-hero',
    title: 'Page hero',
    group: 'components',
    status: 'shipped',
    summary: 'Eyebrow + heading + lede bundle.',
    source: 'route:/ddl/page-hero',
  },
  {
    slug: 'carousel',
    title: 'Carousel',
    group: 'components',
    status: 'shipped',
    summary: 'Touch/drag/keyboard slider with dots & peek.',
    source: 'route:/ddl/carousel',
  },
  {
    slug: 'lightbox',
    title: 'Lightbox',
    group: 'components',
    status: 'shipped',
    summary: 'Full-screen viewer + zoom/pan/carousel.',
    source: 'route:/ddl/lightbox',
  },
  {
    slug: 'show-more',
    title: 'Show more',
    group: 'components',
    status: 'shipped',
    summary: 'Clamp / scroll disclosure, SSR-safe.',
    source: 'route:/ddl/show-more',
  },
  {
    slug: 'scroll-edge-fade',
    title: 'Scroll edge fade',
    group: 'components',
    status: 'shipped',
    summary: 'Overflow fade directive + chevron affordances.',
    source: 'route:/ddl/scroll-edge-fade',
  },
  {
    slug: 'form-lib',
    title: 'Form suite',
    group: 'components',
    status: 'shipped',
    summary: 'Input · textarea · checkbox · radio · form-field.',
    source: 'route:/ddl/form-lib',
  },
  {
    slug: 'form-input',
    title: 'Form input (historical)',
    group: 'components',
    status: 'deprecated',
    summary: 'Early input/textarea visual directions; B shipped.',
    source: 'route:/ddl/form-input',
  },
  {
    slug: 'language-switcher',
    title: 'Language switcher',
    group: 'components',
    status: 'exploring',
    summary: 'Six EN/VI toggle directions.',
    source: 'route:/ddl/language-switcher',
  },
  {
    slug: 'command-palette',
    title: 'Command palette',
    group: 'components',
    status: 'exploring',
    summary: 'Four Cmd+K UX directions.',
    source: 'route:/ddl/command-palette',
  },
  {
    slug: 'mega-menu',
    title: 'Mega-menu',
    group: 'components',
    status: 'exploring',
    summary: 'Six "More" dropdown layout directions.',
    source: 'route:/ddl/mega-menu',
  },
  {
    slug: 'mobile-nav',
    title: 'Mobile nav',
    group: 'components',
    status: 'exploring',
    summary: 'Three full-screen nav sheet looks.',
    source: 'route:/ddl/mobile-nav',
  },
  {
    slug: 'feed-filter-bar',
    title: 'Filter bar',
    group: 'components',
    status: 'exploring',
    summary: 'Year/status/stack filter UX, V1–V4.',
    source: 'route:/ddl/feed-filter-bar',
  },

  // ── Sections ───────────────────────────────────────────────────────────
  {
    slug: 'hero',
    title: 'Hero',
    group: 'sections',
    status: 'decided',
    summary: 'Six hero compositions — α picked.',
    source: 'route:/ddl/hero',
  },
  {
    slug: 'bio',
    title: 'Bio',
    group: 'sections',
    status: 'decided',
    summary: '§3 bio card grid refinements — picks flagged.',
    source: 'route:/ddl/bio',
  },
  {
    slug: 'selected-work',
    title: 'Selected work',
    group: 'sections',
    status: 'exploring',
    summary: 'Four panel-swap motion strategies.',
    source: 'route:/ddl/selected-work',
  },
  {
    slug: 'stack',
    title: 'Stack',
    group: 'sections',
    status: 'exploring',
    summary: 'Tier grouping · brand icons · L3 stagger.',
    source: 'route:/ddl/stack',
  },
  {
    slug: 'story',
    title: 'Story',
    group: 'sections',
    status: 'exploring',
    summary: '§05 four directions — manuscript/journal/spotlight/artifact.',
    source: 'route:/ddl/story',
  },
  {
    slug: 'philosophy-strip',
    title: 'Philosophy strip',
    group: 'sections',
    status: 'exploring',
    summary: '§06b strip — V0 baseline → V4 coda.',
    source: 'route:/ddl/philosophy-strip',
  },
  {
    slug: 'get-in-touch',
    title: 'Get in touch',
    group: 'sections',
    status: 'decided',
    summary: '§07 contact — variant G shipped to home. Verify status.',
    source: 'route:/ddl/get-in-touch',
  },
  {
    slug: 'feed-item',
    title: 'Feed item',
    group: 'sections',
    status: 'exploring',
    summary: 'Row · card · timeline layouts on same data.',
    source: 'route:/ddl/feed-item',
  },
  {
    slug: 'uses-card',
    title: 'Uses card',
    group: 'sections',
    status: 'shipped',
    summary: '/uses tool entries — V2 monogram + S1 graduated.',
    source: 'route:/ddl/uses-card',
  },

  // ── Pages ──────────────────────────────────────────────────────────────
  {
    slug: 'page-shell',
    title: 'Page shell',
    group: 'pages',
    status: 'shipped',
    summary: 'Canonical feature-page composition (mandatory).',
    source: 'route:/ddl/page-shell',
  },
  {
    slug: 'project-detail',
    title: 'Project detail',
    group: 'pages',
    status: 'exploring',
    summary: '5 cover ratios × 4 body layouts.',
    source: 'route:/ddl/project-detail',
  },
  {
    slug: 'blog-list',
    title: 'Blog list',
    group: 'pages',
    status: 'exploring',
    summary: 'Featured-strip V1–V4 + list section.',
    source: 'route:/ddl/blog-list',
  },
  {
    slug: 'blog-detail',
    title: 'Blog detail',
    group: 'pages',
    status: 'exploring',
    summary: 'Editorial · minimal · sticky-rail layouts.',
    source: 'route:/ddl/blog-detail',
  },
  {
    slug: 'about-signatures',
    title: 'About signatures',
    group: 'pages',
    status: 'exploring',
    summary: '/about staging — depth map · failures · shipping.',
    source: 'route:/ddl/about-signatures',
  },

  // ── Patterns ───────────────────────────────────────────────────────────
  {
    slug: 'backgrounds',
    title: 'Backgrounds',
    group: 'patterns',
    status: 'shipped',
    summary: 'Five pure-CSS section backgrounds.',
    source: 'route:/ddl/backgrounds',
  },
  {
    slug: 'fragment-navigation',
    title: 'Fragment navigation',
    group: 'patterns',
    status: 'exploring',
    summary: 'Five in-page nav patterns.',
    source: 'route:/ddl/fragment-navigation',
  },
  {
    slug: 'interactions',
    title: 'Interactions',
    group: 'patterns',
    status: 'exploring',
    summary: 'Micro-interaction wishlist by trigger.',
    source: 'route:/ddl/interactions',
  },
  {
    slug: 'feed-pagination',
    title: 'Pagination strategies',
    group: 'patterns',
    status: 'exploring',
    summary: 'Render-all · load-more · paged trade-offs.',
    source: 'route:/ddl/feed-pagination',
  },
  {
    slug: 'email-templates',
    title: 'Email templates',
    group: 'patterns',
    status: 'exploring',
    summary: 'Auto-reply + admin-notify, sandboxed iframes.',
    source: 'route:/ddl/email-templates',
  },
];
