import type { ProjectListItem, ProjectLifecycleStatus } from '@portfolio/landing/shared/data-access';

/** Mock project list shared across archive DDL sandboxes. Mirror of /api/projects shape. */
export const FAKE_PROJECTS: readonly ProjectListItem[] = [
  {
    slug: 'console-mvp',
    title: 'Console MVP',
    oneLiner: { en: 'The CMS that drives this landing site — auth, profile, projects, skills, media, blog.', vi: '' },
    startDate: '2026-01-01',
    endDate: null,
    thumbnailUrl: 'https://placehold.co/800x500/0a0d12/6e66d9?text=Console',
    skills: [
      { name: 'TypeScript', slug: 'typescript', category: 'TECHNICAL' },
      { name: 'Angular', slug: 'angular', category: 'TECHNICAL' },
      { name: 'NestJS', slug: 'nestjs', category: 'TECHNICAL' },
      { name: 'Prisma', slug: 'prisma', category: 'TECHNICAL' },
      { name: 'PostgreSQL', slug: 'postgresql', category: 'TECHNICAL' },
      { name: 'Figma', slug: 'figma', category: 'TOOL' },
    ],
    featured: true,
    lifecycleStatus: 'LIVE',
  },
  {
    slug: 'document-engine',
    title: 'Document Engine',
    oneLiner: { en: 'PDF rendering pipeline — collect data, paint pages, ship templates.', vi: '' },
    startDate: '2025-08-15',
    endDate: '2025-12-31',
    thumbnailUrl: 'https://placehold.co/800x500/0a0d12/6e66d9?text=DocEngine',
    skills: [
      { name: 'TypeScript', slug: 'typescript', category: 'TECHNICAL' },
      { name: 'NestJS', slug: 'nestjs', category: 'TECHNICAL' },
      { name: 'Puppeteer', slug: 'puppeteer', category: 'TECHNICAL' },
      { name: 'Docker', slug: 'docker', category: 'TOOL' },
    ],
    featured: true,
    lifecycleStatus: 'SHIPPED',
  },
  {
    slug: 'portfolio-v1',
    title: 'Portfolio v1',
    oneLiner: { en: 'This site — Angular SSR, design system, 7-section editorial home.', vi: '' },
    startDate: '2025-11-01',
    endDate: null,
    thumbnailUrl: 'https://placehold.co/800x500/0a0d12/6e66d9?text=Portfolio',
    skills: [
      { name: 'Angular', slug: 'angular', category: 'TECHNICAL' },
      { name: 'Tailwind', slug: 'tailwind', category: 'TECHNICAL' },
      { name: 'SCSS', slug: 'scss', category: 'TECHNICAL' },
      { name: 'Figma', slug: 'figma', category: 'TOOL' },
    ],
    featured: true,
    lifecycleStatus: 'BETA',
  },
  {
    slug: 'sleep-sound-app',
    title: 'Sleep Sound (mobile)',
    oneLiner: { en: 'Native iOS app — looped ambience players + sleep timer.', vi: '' },
    startDate: '2023-04-10',
    endDate: '2023-09-20',
    thumbnailUrl: null,
    skills: [
      { name: 'Swift', slug: 'swift', category: 'TECHNICAL' },
      { name: 'SwiftUI', slug: 'swiftui', category: 'TECHNICAL' },
    ],
    featured: false,
    lifecycleStatus: 'ARCHIVED',
  },
  {
    slug: 'ledger-cli',
    title: 'Ledger CLI',
    oneLiner: { en: 'A plaintext-accounting hobby clone — TUI charts, CSV import.', vi: '' },
    startDate: '2024-02-12',
    endDate: '2024-06-30',
    thumbnailUrl: 'https://placehold.co/800x500/0a0d12/6e66d9?text=Ledger',
    skills: [
      { name: 'Go', slug: 'go', category: 'TECHNICAL' },
      { name: 'Bubble Tea', slug: 'bubbletea', category: 'TECHNICAL' },
    ],
    featured: false,
    lifecycleStatus: 'SHIPPED',
  },
  {
    slug: 'rss-pulse',
    title: 'RSS Pulse',
    oneLiner: { en: 'Self-hosted feed reader with focus mode and weekly digests.', vi: '' },
    startDate: '2024-10-01',
    endDate: null,
    thumbnailUrl: 'https://placehold.co/800x500/0a0d12/6e66d9?text=RSSPulse',
    skills: [
      { name: 'Next.js', slug: 'nextjs', category: 'TECHNICAL' },
      { name: 'React', slug: 'react', category: 'TECHNICAL' },
      { name: 'Postgres', slug: 'postgresql', category: 'TECHNICAL' },
    ],
    featured: false,
    lifecycleStatus: 'ONGOING',
  },
  {
    slug: 'kanban-kit',
    title: 'Kanban Kit',
    oneLiner: { en: 'Drag-and-drop primitives — board / column / card with keyboard a11y.', vi: '' },
    startDate: '2022-11-01',
    endDate: '2023-03-15',
    thumbnailUrl: 'https://placehold.co/800x500/0a0d12/6e66d9?text=Kanban',
    skills: [
      { name: 'React', slug: 'react', category: 'TECHNICAL' },
      { name: 'TypeScript', slug: 'typescript', category: 'TECHNICAL' },
      { name: 'Storybook', slug: 'storybook', category: 'TOOL' },
    ],
    featured: false,
    lifecycleStatus: 'ARCHIVED',
  },
  {
    slug: 'sql-snippets',
    title: 'SQL Snippets',
    oneLiner: { en: 'A curated library of PostgreSQL recipes — window funcs, CTEs, perf.', vi: '' },
    startDate: '2023-06-20',
    endDate: null,
    thumbnailUrl: null,
    skills: [
      { name: 'PostgreSQL', slug: 'postgresql', category: 'TECHNICAL' },
      { name: 'SQL', slug: 'sql', category: 'TECHNICAL' },
    ],
    featured: false,
    lifecycleStatus: 'LIVE',
  },
];

export const LIFECYCLE_STATUSES: readonly ProjectLifecycleStatus[] = ['LIVE', 'SHIPPED', 'ARCHIVED', 'BETA', 'ONGOING'];
