import {
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Check,
  X,
  Menu,
  Search,
  Home,
  User,
  Settings,
  Mail,
  Github,
  Linkedin,
  Twitter,
  ExternalLink,
  Download,
  Sun,
  Moon,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Plus,
  Minus,
  Eye,
  EyeOff,
  Heart,
  Star,
  Briefcase,
  Code,
  Globe,
  Phone,
  ShoppingCart,
  CheckSquare,
  BarChart,
  FolderOpen,
  Image,
  Copy,
  RotateCw,
  Undo2,
  Trash2,
  Archive,
  ArchiveRestore,
  GripVertical,
  CheckCheck,
  RotateCcw,
  MessageSquare,
  ChevronsDownUp,
  ChevronsUpDown,
  ListChecks,
  ListX,
  Filter,
  SlidersHorizontal,
  LayoutGrid,
  List,
  History,
  FileX,
  LucideIconData,
  Link,
  Package,
  FilePen,
  PenLine,
  Wrench,
  Layers,
  Palette,
  FileDown,
  LogIn,
  LogOut,
  CloudCheck,
  CloudAlert,
  CloudOff,
  CloudUpload,
  LoaderCircle,
  FileText,
  Folder,
} from 'lucide-angular';
import { IconProvider } from '../icon-provider.interface';

const ICON_MAP: Record<string, LucideIconData> = {
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  check: Check,
  close: X,
  x: X,
  menu: Menu,
  search: Search,
  home: Home,
  user: User,
  settings: Settings,
  mail: Mail,
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  'external-link': ExternalLink,
  download: Download,
  sun: Sun,
  moon: Moon,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  plus: Plus,
  minus: Minus,
  eye: Eye,
  'eye-off': EyeOff,
  heart: Heart,
  star: Star,
  briefcase: Briefcase,
  code: Code,
  globe: Globe,
  phone: Phone,
  'shopping-cart': ShoppingCart,
  'check-square': CheckSquare,
  'bar-chart': BarChart,
  'folder-open': FolderOpen,
  image: Image,
  copy: Copy,
  'rotate-cw': RotateCw,
  'undo-2': Undo2,
  'trash-2': Trash2,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'grip-vertical': GripVertical,
  'check-check': CheckCheck,
  'rotate-ccw': RotateCcw,
  'message-square': MessageSquare,
  'chevrons-down-up': ChevronsDownUp,
  'chevrons-up-down': ChevronsUpDown,
  'list-checks': ListChecks,
  'list-x': ListX,
  filter: Filter,
  'sliders-horizontal': SlidersHorizontal,
  'layout-grid': LayoutGrid,
  list: List,
  history: History,
  'file-x': FileX,
  link: Link,
  package: Package,
  'file-pen': FilePen,
  'pen-line': PenLine,
  wrench: Wrench,
  layers: Layers,
  palette: Palette,
  'file-down': FileDown,
  'log-in': LogIn,
  'log-out': LogOut,
  'cloud-check': CloudCheck,
  'cloud-alert': CloudAlert,
  'cloud-off': CloudOff,
  'cloud-upload': CloudUpload,
  'loader-circle': LoaderCircle,
  'file-text': FileText,
  folder: Folder,
};

export class LucideIconProvider implements IconProvider {
  getSvg(name: string, size: number): string | null {
    const iconData = ICON_MAP[name];
    if (!iconData) return null;

    const children = iconData
      .map(([tag, attrs]) => {
        const attrStr = Object.entries(attrs)
          .filter(([key]) => key !== 'key')
          .map(([key, value]) => `${key}="${value}"`)
          .join(' ');
        return `<${tag} ${attrStr} />`;
      })
      .join('');

    return (
      `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" ` +
      `viewBox="0 0 24 24" fill="none" stroke="currentColor" ` +
      `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">` +
      `${children}</svg>`
    );
  }

  getSupportedIcons(): string[] {
    return Object.keys(ICON_MAP);
  }
}

export const lucideProvider = new LucideIconProvider();
