export enum BlogPostErrorCode {
  NOT_FOUND = 'BLOG_POST_NOT_FOUND',
  SLUG_CONFLICT = 'BLOG_POST_SLUG_CONFLICT',
  INVALID_STATUS_TRANSITION = 'BLOG_POST_INVALID_STATUS_TRANSITION',
  CONTENT_REQUIRED = 'BLOG_POST_CONTENT_REQUIRED',
}
