export enum CategoryErrorCode {
  NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INVALID_INPUT = 'CATEGORY_INVALID_INPUT',
  NAME_TAKEN = 'CATEGORY_NAME_TAKEN',
  ALREADY_DELETED = 'CATEGORY_ALREADY_DELETED',
}
