export enum ChecklistErrorCode {
  INVALID_INPUT = 'CHECKLIST_INVALID_INPUT',
  INVALID_MARKDOWN = 'CHECKLIST_INVALID_MARKDOWN',
  UNKNOWN_FILE = 'CHECKLIST_UNKNOWN_FILE',
  DOC_NOT_FOUND = 'CHECKLIST_DOC_NOT_FOUND',
  DOC_ARCHIVED = 'CHECKLIST_DOC_ARCHIVED',
  RUN_NOT_FOUND = 'CHECKLIST_RUN_NOT_FOUND',
  RUN_VERSION_CONFLICT = 'CHECKLIST_RUN_VERSION_CONFLICT',
}
