export enum ContactMessageErrorCode {
  NOT_FOUND = 'CONTACT_MESSAGE_NOT_FOUND',
  INVALID_INPUT = 'CONTACT_MESSAGE_INVALID_INPUT',
  ALREADY_DELETED = 'CONTACT_MESSAGE_ALREADY_DELETED',
  ALREADY_ARCHIVED = 'CONTACT_MESSAGE_ALREADY_ARCHIVED',
  INVALID_TRANSITION = 'CONTACT_MESSAGE_INVALID_TRANSITION',
  RATE_LIMITED = 'CONTACT_MESSAGE_RATE_LIMITED',
  DISPOSABLE_EMAIL = 'CONTACT_MESSAGE_DISPOSABLE_EMAIL',
  SPAM_DETECTED = 'CONTACT_MESSAGE_SPAM_DETECTED',
}
