export enum MediaErrorCode {
  NOT_FOUND = 'MEDIA_NOT_FOUND',
  INVALID_INPUT = 'MEDIA_INVALID_INPUT',
  ALREADY_DELETED = 'MEDIA_ALREADY_DELETED',
  NOT_DELETED = 'MEDIA_NOT_DELETED',
  FILE_TOO_LARGE = 'MEDIA_FILE_TOO_LARGE',
  UNSUPPORTED_TYPE = 'MEDIA_UNSUPPORTED_TYPE',
  UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  DELETE_FAILED = 'MEDIA_DELETE_FAILED',
  SECURITY_THREAT = 'MEDIA_SECURITY_THREAT',
}
