export enum ProjectErrorCode {
  NOT_FOUND = 'PROJECT_NOT_FOUND',
  INVALID_INPUT = 'PROJECT_INVALID_INPUT',
  SLUG_CONFLICT = 'PROJECT_SLUG_CONFLICT',
  MAX_HIGHLIGHTS_EXCEEDED = 'PROJECT_MAX_HIGHLIGHTS_EXCEEDED',
}
