export enum RadarErrorCode {
  SOURCE_NOT_FOUND = 'RADAR_SOURCE_NOT_FOUND',
  SOURCE_URL_TAKEN = 'RADAR_SOURCE_URL_TAKEN',
  SOURCE_INACTIVE = 'RADAR_SOURCE_INACTIVE',
  ITEM_NOT_FOUND = 'RADAR_ITEM_NOT_FOUND',
  INVALID_INPUT = 'RADAR_INVALID_INPUT',
  INVALID_UPLOAD = 'RADAR_INVALID_UPLOAD',
  IMAGE_DELETE_FAILED = 'RADAR_IMAGE_DELETE_FAILED',
}
