export enum SkillErrorCode {
  NOT_FOUND = 'SKILL_NOT_FOUND',
  INVALID_INPUT = 'SKILL_INVALID_INPUT',
  NAME_TAKEN = 'SKILL_NAME_TAKEN',
  ALREADY_DELETED = 'SKILL_ALREADY_DELETED',
  CIRCULAR_REFERENCE = 'SKILL_CIRCULAR_REFERENCE',
  MAX_DEPTH_EXCEEDED = 'SKILL_MAX_DEPTH_EXCEEDED',
  PARENT_DELETED = 'SKILL_PARENT_DELETED',
  HAS_CHILDREN = 'SKILL_HAS_CHILDREN',
}
