export enum UserErrorCode {
  NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_INPUT = 'USER_INVALID_INPUT',
  EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  ACCESS_DENIED = 'USER_ACCESS_DENIED',
  ALREADY_ACTIVATED = 'USER_ALREADY_ACTIVATED',
  ALREADY_DELETED = 'USER_ALREADY_DELETED',
}
